alias mntwn='sudo mount -o ro /dev/sda2 /mnt/windows'
alias l='ls -CF --group-directories-first'
alias ll='ls -alF --group-directories-first'
alias ls='ls -F --color=auto --group-directories-first'
alias chrome='google-chrome'
